2019-11-17 18:58:36.200 [error] <0.1389.0> CRASH REPORT Process <0.1389.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 199,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gzip">>,<<"connection">> => <<"upgrade">>,<<"content-length">> => <<"199">>,<<"content-type">> => <<"application/x-www-form-urlencoded; charset=UTF-8">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 18:58:36.201 [error] <0.1387.0> CRASH REPORT Process <0.1387.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gzip">>,<<"connection">> => <<"upgrade">>,<<"content-length">> => <<"14">>,<<"content-type">> => <<"application/x-www-form-urlencoded; charset=UTF-8">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 18:58:36.201 [error] <0.1391.0> CRASH REPORT Process <0.1391.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gzip">>,<<"connection">> => <<"upgrade">>,<<"content-length">> => <<"232">>,<<"content-type">> => <<"application/x-www-form-urlencoded; charset=UTF-8">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 18:58:36.263 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1390.0>,1,<0.1391.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gzip">>,<<"connection">> => <<"upgrade">>,<<"content-length">> => <<"23...">>,...},...}},...},...},...},...},...]},...}}
