2019-11-16 16:42:06.608 [error] <0.1598.0> CRASH REPORT Process <0.1598.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"company-api.domoface.ru">>,<<"referer">> => <<"https://company-api.domoface.ru/">>,<<...>> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-16 16:42:06.616 [error] <0.1597.0> CRASH REPORT Process <0.1597.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"company-api.domoface.ru">>,<<"referer">> => <<"https://company-api.domoface.ru/">>,<<"user-agent">> => <<"M...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-16 16:42:06.622 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiWeb.Endpoint.HTTP',<0.1595.0>,1,<0.1597.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"company-api.domoface.ru">>,...},...}},...},...},...},...},...]},...}}
2019-11-16 16:42:06.653 [error] <0.1601.0> CRASH REPORT Process <0.1601.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"company-api.domoface.ru">>,<<"referer">> => <<"https://company-api.domoface.ru/">>,<<"user-agent">> => <<"Mozilla/5.0 (Win...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-16 16:42:06.659 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiWeb.Endpoint.HTTP',<0.1600.0>,1,<0.1601.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"company-api.domoface.ru">>,<<"refere...">> => ...,...},...}},...},...},...},...},...]},...}}
